apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring 
    spec:
      imagePullSecrets:
      - name: $SECRET_NAME 
      containers:
      - name: spring 
        image: $IMAGE_NAME 
        ports:
        - containerPort: 8091
          name: spring
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 80
        #  initialDelaySeconds: 60
        #  timeoutSeconds: 10
        #  failureThreshold: 5
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: 80
        #  initialDelaySeconds: 60
        #  timeoutSeconds: 10
        #  failureThreshold: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1024Mi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8091
      name: spring

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - spring.scm.local
    #secretName: dimpleblog-ingress-secret
  rules:
  - host: spring.scm.local
    http:
      paths:
      - path:
        backend:
          serviceName: spring
          servicePort: 80
